### ISSUE TITLE
Why to use wait-for-it, when docker-compose has depends_on and healthchecks?

### ISSUE THREAD

**Issue by leon0399** [dailydotdev/apps#635]
Hi! That's just a question, not a big deal, but why to use `wait-for-it.sh`, instead of [`healthcheck`](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck) and [`depends_on`](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on). 

For example, there is how it could be used:

```yaml
daily-postgres:
  ...
  test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
  ...

daily-api:
  ...
  depends_on:
      daily-postgres:
        condition: service_healthy
  ...
```

I personally use it in all my own projects, and it works great, and in theory, even better then `wait-for-it.sh`, since it can be configured in any way you want
